### ISSUE TITLE
Pool.getConnection got problem on node 4.2.x

### ISSUE THREAD

**Issue by sikancil** [neumino/rethinkdbdash#172]
**Test Environments:**
* NodeJS v4.2.1
* Hapi v11.0.3
* RethinkDB 2.1.4~0trusty (GCC 4.8.2)
* thinky v2.1.11

##### Shell output:
```
Warning: a promise was created in a  handler but was not returned from it
    at Pool.getConnection (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool.js:72:11)
    at Pool.<anonymous> (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool_master.js:405:12)
    at emitOne (events.js:77:13)
    at Pool.emit (events.js:169:7)
    at Pool.putConnection (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool.js:164:10)
    at /home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool.js:277:10
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

Issue was posted to thinky, please refer to: [https://github.com/neumino/thinky/issues/379] (https://github.com/neumino/thinky/issues/379)

**Comment by neumino** [comment]
Like mentioned in the other issue, this is just a warning. I'll clean the handler though

**Comment by neumino** [comment]
Should be fixed in 2.1.16

**Comment by ppascher** [comment]
I still get that message (though not as frequently) after updating. Could it be because I use thinky with await ?
```
const user = await User.get(ctx.params.id).run();
```
```
Warning: a promise was created in a  handler but was not returned from it
    at Cursor._next (/projects/intranet_redux/backend/node_modules/rethinkdbdash/lib/cursor.js:52:11)
    at resolve (/projects/intranet_redux/backend/node_modules/rethinkdbdash/lib/cursor.js:228:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Cursor._each (/projects/intranet_redux/backend/node_modules/rethinkdbdash/lib/cursor.js:238:16)
    at /projects/intranet_redux/backend/node_modules/rethinkdbdash/lib/cursor.js:96:10
From previous event:
    at Cursor.toArray (/projects/intranet_redux/backend/node_modules/rethinkdbdash/lib/cursor.js:93:11)
    at Connection._processResponse (/projects/intranet_redux/backend/node_modules/rethinkdbdash/lib/connection.js:444:16)
    at Socket.<anonymous> (/projects/intranet_redux/backend/node_modules/rethinkdbdash/lib/connection.js:150:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```
```
└─┬ thinky@2.1.11
  ├── bluebird@2.1.3
  ├─┬ rethinkdbdash@2.1.16
  │ └── bluebird@3.0.5
  └── validator@3.22.2
```

**Comment by neumino** [comment]
Pushed 2.1.17 -- I believe it should fix this case. @ppascher let me know if it's not the case

**Comment by ppascher** [comment]
No more warnings, thanks alot @neumino

**Comment by sc0ttyd** [comment]
I'm still getting something similar, on 2.1.17:

Warning: a promise was created in a  handler but was not returned from it
    at processImmediate [as _immediateCallback] (timers.js:368:17)
From previous event:
    at Term.run (/Users/scotty/workspace/cm/oauth_server/node_modules/rethinkdbdash/lib/term.js:145:21)

**Comment by neumino** [comment]
Can you provide a full script that triggers this warning?

**Comment by roblav96** [comment]
```
c-0  Warning: a promise was created in a  handler but was not returned from it
c-0     at Term.run (/Users/roblav96/Projects/app/server/node_modules/rethinkdbdash/lib/term.js:145:21)
c-0     at /Users/roblav96/Projects/app/server/src/routes/public/register.js:41:36
c-0 From previous event:
c-0     at Server.module.exports (/Users/roblav96/Projects/app/server/src/routes/public/register.js:16:45)
c-0     at next (/Users/roblav96/Projects/app/server/node_modules/restify/lib/server.js:906:30)
c-0     at f (/Users/roblav96/Projects/app/server/node_modules/once/once.js:17:25)
c-0     at /Users/roblav96/Projects/app/server/src/middle/public/verify-initKey.js:24:4
c-0     at bound (domain.js:280:14)
c-0     at runBound (domain.js:293:12)
c-0 From previous event:
c-0     at /Users/roblav96/Projects/app/server/src/middle/public/verify-initKey.js:22:88
c-0     at bound (domain.js:280:14)
c-0     at runBound (domain.js:293:12)
c-0     at tryCatcher (/Users/roblav96/Projects/app/server/node_modules/ioredis/node_modules/bluebird/js/main/util.js:26:23)
c-0     at Promise._settlePromiseFromHandler (/Users/roblav96/Projects/app/server/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:507:31)
c-0     at Promise._settlePromiseAt (/Users/roblav96/Projects/app/server/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:581:18)
c-0     at Promise._settlePromises (/Users/roblav96/Projects/app/server/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:697:14)
c-0     at Async._drainQueue (/Users/roblav96/Projects/app/server/node_modules/ioredis/node_modules/bluebird/js/main/async.js:123:16)
c-0     at Async._drainQueues (/Users/roblav96/Projects/app/server/node_modules/ioredis/node_modules/bluebird/js/main/async.js:133:10)
c-0     at Immediate.Async.drainQueues [as _onImmediate] (/Users/roblav96/Projects/app/server/node_modules/ioredis/node_modules/bluebird/js/main/async.js:15:14)
c-0     at processImmediate [as _immediateCallback] (timers.js:383:17)
```
