### ISSUE TITLE
Warning: a promise was created in a handler at lib/pool.js:248:14 but was not returned from it.

### ISSUE THREAD

**Issue by meenie** [neumino/rethinkdbdash#285]
I'm using `thinky#2.3.6` and that pulled down `rethinkdbdash#2.3.21`.  I only ran into this when I started to use the `pingInterval` option. 

Here's the full error:

```
(node:46024) Warning: a promise was created in a handler at `node_modules/rethinkdbdash/lib/pool.js:248:14` but was not returned from it, see http://goo.gl/rRqMUw
      at new Promise (`./node_modules/rethinkdbdash/node_modules/bluebird/js/release/promise.js:77:14`)
```

To fix it, I put in return statements at the line specified above, and also on line: 321.  Not sure that is the correct fix though, so I haven't created a PR.

**Comment by neumino** [comment]
Fixed in 2.3.22

**Comment by nopnop** [comment]
Hi @neumino,

There is still some un-returned promise  (such [as here](https://github.com/neumino/rethinkdbdash/blob/86aaf3476a4df874286d622f56728b48c4f38049/lib/cursor.js#L300)) - Which throw many warning when toStream is used.

**Comment by meenie** [comment]
@neumino Your fix didn't fix it fully.  `Pool.prototype._expandBuffer` needs to return something as well.  The PR I had open did actually fix it.

**Comment by meenie** [comment]
@neumino Just bumping this up again. Need to re-open this issue.

**Comment by neumino** [comment]
Can you send a PR?

**Comment by meenie** [comment]
@neumino This is the PR I originally had: https://github.com/neumino/rethinkdbdash/pull/286
